env:
  global:
    - CC_TEST_REPORTER_ID=2a88c52cdde8ecf7e3854c838b33630478612b34da7bcf12f574ab1c04e3a232
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'
  - 'nightly'

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - if [ $(phpenv version-name) = "7.3" ]; then ./cc-test-reporter before-build; fi

install: composer install

script: 'XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover clover.xml'

after_script:
  - 'if [ $(phpenv version-name) = "7.3" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT; fi'
